### PR TITLE
Here's a commit

### PR DESCRIPTION
**Pull request by bishoprook**
Added a MockResponseConsumer capable of some rudimentary eventing, and used it to flesh out AccountSessionTest.cs.

How do you want to handle pushes?  Fork/pull request, or just email you the diff, or contributor on the main project?

### CODE REVIEW

**Comment by bishoprook** [comment]
I like the black-boxy tests better.

**Comment by jwodicka** [comment]
Looks good to me. 

Consider on how we can pull out some of those helper routines into something that's more broadly applicable; I think we will want to refactor them to someplace common, since we've got similar routines in one of the other tests too.

That's no reason to block this commit, however. I'm pulling.

**Comment by jwodicka** [comment]
(Apparently your pull request description becomes the commit message. So, next time probably use one that's more semantic. Now we know.)

**Comment by bishoprook** [comment]
And knowing is half the battle!

**Comment by jwodicka** [comment]
Or maybe it didn't. Huh. The UI around that message is a little weird.
Anyway, doesn't hurt to have it be a description of the feature we're
integrating. =)

**Comment by bishoprook** [comment]
It might also be useful to write up a few issues to put on the issues page.  You can associate pull requests with issues, and get added traceability that way.  Maybe just take a look at some of the TODOs, group them together by subject, and put them up.

**Pull request merged**
