### PR TITLE
Migration to Ninject IoC container

### PR DESCRIPTION
**Pull request by bishoprook**
I tried to identify the existing dependencies in the project and I think I got most of them.  A couple things are still wonky and we'll need to look at them: the hardcoded SQLiteAccountStore and CharacterOwnershipIndex are both still baked in, they're just injected instead of instantiated on demand.  Should make it easier to swap them out later.

One thing that makes me kind of go "ehh" is the AccountFactory and CharacterFactory.  The issue here is: the current implementation of Account and Character use instance-specific state (name, password, worldname) but they also use an injected dependency (CharacterOwnershipIndex).  There's no easy way to instantiate a new Character or Account via a constructor and still get the dependency injected by the IoC container.  But we can use a factory method.  Still, I'd like to examine these classes and see if we can't remove the dependency on CharacterOwnershipIndex from them and thereby eliminate the need for the factory classes.

I did some cleanup as well: there were cases of properties that could just be private fields, because the property only enforced non-nullness and the constructor is capable of doing that.  If that was a deliberate design decision, I can change it back, though I'd like to discuss it if so!

### CODE REVIEW

**Comment by jwodicka** [comment]
So, talking out the dependency that Character and Account have on CharacterOwnershipIndex:

They basically have this dependency to make the semantics of character.CanBeAccessedByUser(user) and account.CanAccessCharacter(character, world) work. I'm wondering if we can do something like the WithMockSource methods we use for testing, to request the CharacterOwnershipIndex at the time the request is made? Something feels faintly unclean about this, though; it has the smell of Singleton about it.

Alternatively, maybe it's okay to factor it away from the objects themselves, so you cannot ask "Character, does this User have access to you?," but instead have to ask "Access Manager, does this User have access to this Character?" It reduces the coupling between Character, Account, and CharacterOwnershipIndex, but at the cost that what feels like a logical operation on either Character or Account (asking about ownership and rights) is suddenly the responsibility of a third party entirely.

I think Singleton smells bad to me here because I can envision a world in which different characters might be operating under different rules for ownership-management - different worlds might have different backing stores for ownership. The problem may be that we actually should be making Character construction the responsibility of the World - since every character exists at the intersection of a World and an identifier, maybe the problem is that we're currently letting non-World things create characters. What would it do to the code if we didn't have a CharacterFactory, but instead made Character creation a responsibility of the World? Then the World has to have a CharacterOwnershipIndex, which it acquires from the IoC container and hands on to the Characters it creates.

In this universe, then, Account's CanAccessCharacter method is actually a convenience wrapper; it just calls character.CanBeAccessedByAccount(this); and returns the result. Account no longer needs a reference to the CharacterOwnershipIndex, which is good, because an Account might actually have information in multiple ownership indices, if different worlds have them. Account's ability to have a single CharacterOwnershipIndex is entirely an artifact of the fact that the CharacterOwnershipIndex is currently a singleton.

Of course, this means we need to be a little more diligent than we have been about using a Character object instead of a pair of (characterName, worldName) strings - but that's probably better design, anyway.

Opinions? What haven't I considered here?

**Comment by jwodicka** [comment]
Also, as far as the private properties / private fields thing goes: at one point, I was of the opinion that code should touch fields as little as possible - but on examination, I'm not sure _why_ I felt that way. It's probably cleaner to use the fields directly, if we're not making any special use of what properties give us. Certainly, I don't want to have public fields, and I often don't want fields if I expect to be subclassed and want the child to be poking at the contents of the field - in both those cases, I feel like properties enforce a stylistic separation between implementation and interface. But for a private field, there really isn't a meaningful notion of interface, so I don't see much cause to enforce separation.

Which is a longwinded way of saying "I like your changes; let's go with them."

**Comment by jwodicka** [comment]
One last thing: Can you pull the latest version of mainline to your branch, merge and test, before I pull? You've got a better handle on the IoC than I do, and a couple of parts of the code have changed somewhat radically since the spot you forked from. I'd rather have you do the merge than me; I think you're more likely to get it right.

**Comment by bishoprook** [comment]
I will do that merging tomorrow at latest.
On Sep 14, 2011 6:59 PM, "Jason Wodicka" <
reply@reply.github.com>
wrote:

**Comment by bishoprook** [comment]
Yay merging.

**Comment by jwodicka** [comment]
Awesome. We have clean merge.

Pulling this in now, and we can consider what we were discussing about refactoring the Factories as a cleanup work-item.

**Pull request merged**
